//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BecasLexer.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class BecasLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		START=1, END=2, VAR=3, LOOP=4, IN=5, RANGE=6, CHECK=7, IF=8, SO=9, ELSEIF=10, 
		ELSE=11, END_CHECK=12, END_LOOP=13, OUT=14, INPUT=15, OP_ASIG=16, OP_ARIT=17, 
		OP_REL=18, OP_OR=19, OP_AND=20, OP_NOT=21, PARENT_I=22, PARENT_D=23, COLON=24, 
		COMMA=25, ID=26, INT=27, FLOAT=28, STRING=29, COMMENT=30, WS=31;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"START", "END", "VAR", "LOOP", "IN", "RANGE", "CHECK", "IF", "SO", "ELSEIF", 
		"ELSE", "END_CHECK", "END_LOOP", "OUT", "INPUT", "OP_ASIG", "OP_ARIT", 
		"OP_REL", "OP_OR", "OP_AND", "OP_NOT", "PARENT_I", "PARENT_D", "COLON", 
		"COMMA", "ID", "INT", "FLOAT", "STRING", "COMMENT", "WS"
	};


	public BecasLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public BecasLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, "'END'", "'VAR'", "'LOOP'", "'IN'", "'range'", "'CHECK'", 
		"'IF'", "'SO'", "'ELSEIF'", "'ELSE'", "'END_CHECK'", "'END_LOOP'", "'OUT'", 
		"'INPUT'", "'='", "'+'", null, null, "'&&'", "'!'", "'('", "')'", "':'", 
		"','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "START", "END", "VAR", "LOOP", "IN", "RANGE", "CHECK", "IF", "SO", 
		"ELSEIF", "ELSE", "END_CHECK", "END_LOOP", "OUT", "INPUT", "OP_ASIG", 
		"OP_ARIT", "OP_REL", "OP_OR", "OP_AND", "OP_NOT", "PARENT_I", "PARENT_D", 
		"COLON", "COMMA", "ID", "INT", "FLOAT", "STRING", "COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "BecasLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static BecasLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '!', '\xE7', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x5', '\x2', 'K', '\n', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x5', '\x13', '\xA0', '\n', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x5', '\x14', '\xA5', '\n', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\a', '\x1B', 
		'\xB6', '\n', '\x1B', '\f', '\x1B', '\xE', '\x1B', '\xB9', '\v', '\x1B', 
		'\x3', '\x1C', '\x6', '\x1C', '\xBC', '\n', '\x1C', '\r', '\x1C', '\xE', 
		'\x1C', '\xBD', '\x3', '\x1D', '\x6', '\x1D', '\xC1', '\n', '\x1D', '\r', 
		'\x1D', '\xE', '\x1D', '\xC2', '\x3', '\x1D', '\x3', '\x1D', '\x6', '\x1D', 
		'\xC7', '\n', '\x1D', '\r', '\x1D', '\xE', '\x1D', '\xC8', '\x3', '\x1E', 
		'\x3', '\x1E', '\a', '\x1E', '\xCD', '\n', '\x1E', '\f', '\x1E', '\xE', 
		'\x1E', '\xD0', '\v', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\a', '\x1F', '\xD8', '\n', 
		'\x1F', '\f', '\x1F', '\xE', '\x1F', '\xDB', '\v', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x6', ' ', '\xE2', 
		'\n', ' ', '\r', ' ', '\xE', ' ', '\xE3', '\x3', ' ', '\x3', ' ', '\x4', 
		'\xCE', '\xD9', '\x2', '!', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', 
		'\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', 
		'\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', 
		'\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', 
		'\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', 
		'\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', 
		' ', '?', '!', '\x3', '\x2', '\x6', '\x5', '\x2', '\x43', '\\', '\x61', 
		'\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', 
		'\x61', '\x63', '|', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\v', '\f', 
		'\xF', '\xF', '\"', '\"', '\x2', '\xF0', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x3', 'J', '\x3', '\x2', '\x2', '\x2', '\x5', 'L', '\x3', '\x2', 
		'\x2', '\x2', '\a', 'P', '\x3', '\x2', '\x2', '\x2', '\t', 'T', '\x3', 
		'\x2', '\x2', '\x2', '\v', 'Y', '\x3', '\x2', '\x2', '\x2', '\r', '\\', 
		'\x3', '\x2', '\x2', '\x2', '\xF', '\x62', '\x3', '\x2', '\x2', '\x2', 
		'\x11', 'h', '\x3', '\x2', '\x2', '\x2', '\x13', 'k', '\x3', '\x2', '\x2', 
		'\x2', '\x15', 'n', '\x3', '\x2', '\x2', '\x2', '\x17', 'u', '\x3', '\x2', 
		'\x2', '\x2', '\x19', 'z', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x84', 
		'\x3', '\x2', '\x2', '\x2', '\x1D', '\x8D', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', '\x91', '\x3', '\x2', '\x2', '\x2', '!', '\x97', '\x3', '\x2', 
		'\x2', '\x2', '#', '\x99', '\x3', '\x2', '\x2', '\x2', '%', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\'', '\xA4', '\x3', '\x2', '\x2', '\x2', ')', '\xA6', 
		'\x3', '\x2', '\x2', '\x2', '+', '\xA9', '\x3', '\x2', '\x2', '\x2', '-', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '/', '\xAD', '\x3', '\x2', '\x2', 
		'\x2', '\x31', '\xAF', '\x3', '\x2', '\x2', '\x2', '\x33', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\xB3', '\x3', '\x2', '\x2', '\x2', '\x37', 
		'\xBB', '\x3', '\x2', '\x2', '\x2', '\x39', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', ';', '\xCA', '\x3', '\x2', '\x2', '\x2', '=', '\xD3', '\x3', '\x2', 
		'\x2', '\x2', '?', '\xE1', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', 
		'\a', 'U', '\x2', '\x2', '\x42', '\x43', '\a', 'V', '\x2', '\x2', '\x43', 
		'\x44', '\a', '\x43', '\x2', '\x2', '\x44', '\x45', '\a', 'T', '\x2', 
		'\x2', '\x45', 'K', '\a', 'V', '\x2', '\x2', '\x46', 'G', '\a', 'U', '\x2', 
		'\x2', 'G', 'H', '\a', 'V', '\x2', '\x2', 'H', 'I', '\a', '\x43', '\x2', 
		'\x2', 'I', 'K', '\a', 'T', '\x2', '\x2', 'J', '\x41', '\x3', '\x2', '\x2', 
		'\x2', 'J', '\x46', '\x3', '\x2', '\x2', '\x2', 'K', '\x4', '\x3', '\x2', 
		'\x2', '\x2', 'L', 'M', '\a', 'G', '\x2', '\x2', 'M', 'N', '\a', 'P', 
		'\x2', '\x2', 'N', 'O', '\a', '\x46', '\x2', '\x2', 'O', '\x6', '\x3', 
		'\x2', '\x2', '\x2', 'P', 'Q', '\a', 'X', '\x2', '\x2', 'Q', 'R', '\a', 
		'\x43', '\x2', '\x2', 'R', 'S', '\a', 'T', '\x2', '\x2', 'S', '\b', '\x3', 
		'\x2', '\x2', '\x2', 'T', 'U', '\a', 'N', '\x2', '\x2', 'U', 'V', '\a', 
		'Q', '\x2', '\x2', 'V', 'W', '\a', 'Q', '\x2', '\x2', 'W', 'X', '\a', 
		'R', '\x2', '\x2', 'X', '\n', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', 
		'K', '\x2', '\x2', 'Z', '[', '\a', 'P', '\x2', '\x2', '[', '\f', '\x3', 
		'\x2', '\x2', '\x2', '\\', ']', '\a', 't', '\x2', '\x2', ']', '^', '\a', 
		'\x63', '\x2', '\x2', '^', '_', '\a', 'p', '\x2', '\x2', '_', '`', '\a', 
		'i', '\x2', '\x2', '`', '\x61', '\a', 'g', '\x2', '\x2', '\x61', '\xE', 
		'\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\a', '\x45', '\x2', '\x2', 
		'\x63', '\x64', '\a', 'J', '\x2', '\x2', '\x64', '\x65', '\a', 'G', '\x2', 
		'\x2', '\x65', '\x66', '\a', '\x45', '\x2', '\x2', '\x66', 'g', '\a', 
		'M', '\x2', '\x2', 'g', '\x10', '\x3', '\x2', '\x2', '\x2', 'h', 'i', 
		'\a', 'K', '\x2', '\x2', 'i', 'j', '\a', 'H', '\x2', '\x2', 'j', '\x12', 
		'\x3', '\x2', '\x2', '\x2', 'k', 'l', '\a', 'U', '\x2', '\x2', 'l', 'm', 
		'\a', 'Q', '\x2', '\x2', 'm', '\x14', '\x3', '\x2', '\x2', '\x2', 'n', 
		'o', '\a', 'G', '\x2', '\x2', 'o', 'p', '\a', 'N', '\x2', '\x2', 'p', 
		'q', '\a', 'U', '\x2', '\x2', 'q', 'r', '\a', 'G', '\x2', '\x2', 'r', 
		's', '\a', 'K', '\x2', '\x2', 's', 't', '\a', 'H', '\x2', '\x2', 't', 
		'\x16', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', 'G', '\x2', '\x2', 
		'v', 'w', '\a', 'N', '\x2', '\x2', 'w', 'x', '\a', 'U', '\x2', '\x2', 
		'x', 'y', '\a', 'G', '\x2', '\x2', 'y', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'z', '{', '\a', 'G', '\x2', '\x2', '{', '|', '\a', 'P', '\x2', '\x2', 
		'|', '}', '\a', '\x46', '\x2', '\x2', '}', '~', '\a', '\x61', '\x2', '\x2', 
		'~', '\x7F', '\a', '\x45', '\x2', '\x2', '\x7F', '\x80', '\a', 'J', '\x2', 
		'\x2', '\x80', '\x81', '\a', 'G', '\x2', '\x2', '\x81', '\x82', '\a', 
		'\x45', '\x2', '\x2', '\x82', '\x83', '\a', 'M', '\x2', '\x2', '\x83', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', 'G', '\x2', 
		'\x2', '\x85', '\x86', '\a', 'P', '\x2', '\x2', '\x86', '\x87', '\a', 
		'\x46', '\x2', '\x2', '\x87', '\x88', '\a', '\x61', '\x2', '\x2', '\x88', 
		'\x89', '\a', 'N', '\x2', '\x2', '\x89', '\x8A', '\a', 'Q', '\x2', '\x2', 
		'\x8A', '\x8B', '\a', 'Q', '\x2', '\x2', '\x8B', '\x8C', '\a', 'R', '\x2', 
		'\x2', '\x8C', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'Q', '\x2', '\x2', '\x8E', '\x8F', '\a', 'W', '\x2', '\x2', '\x8F', '\x90', 
		'\a', 'V', '\x2', '\x2', '\x90', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\x92', '\a', 'K', '\x2', '\x2', '\x92', '\x93', '\a', 'P', '\x2', '\x2', 
		'\x93', '\x94', '\a', 'R', '\x2', '\x2', '\x94', '\x95', '\a', 'W', '\x2', 
		'\x2', '\x95', '\x96', '\a', 'V', '\x2', '\x2', '\x96', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\x97', '\x98', '\a', '?', '\x2', '\x2', '\x98', '\"', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '-', '\x2', '\x2', '\x9A', 
		'$', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\a', '>', '\x2', '\x2', 
		'\x9C', '\xA0', '\a', '?', '\x2', '\x2', '\x9D', '\x9E', '\a', '@', '\x2', 
		'\x2', '\x9E', '\xA0', '\a', '?', '\x2', '\x2', '\x9F', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'&', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\a', '~', '\x2', '\x2', 
		'\xA2', '\xA5', '\a', '~', '\x2', '\x2', '\xA3', '\xA5', '\a', '~', '\x2', 
		'\x2', '\xA4', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '\xA5', '(', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\xA7', '\a', '(', '\x2', '\x2', '\xA7', '\xA8', '\a', '(', '\x2', '\x2', 
		'\xA8', '*', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\a', '#', '\x2', 
		'\x2', '\xAA', ',', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\a', 
		'*', '\x2', '\x2', '\xAC', '.', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', 
		'\a', '+', '\x2', '\x2', '\xAE', '\x30', '\x3', '\x2', '\x2', '\x2', '\xAF', 
		'\xB0', '\a', '<', '\x2', '\x2', '\xB0', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xB2', '\a', '.', '\x2', '\x2', '\xB2', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB7', '\t', '\x2', '\x2', '\x2', '\xB4', 
		'\xB6', '\t', '\x3', '\x2', '\x2', '\xB5', '\xB4', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xB7', '\xB5', '\x3', 
		'\x2', '\x2', '\x2', '\xB7', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xB8', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xBA', '\xBC', '\t', '\x4', '\x2', '\x2', '\xBB', '\xBA', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xBB', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\x38', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC1', '\t', 
		'\x4', '\x2', '\x2', '\xC0', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC1', 
		'\xC2', '\x3', '\x2', '\x2', '\x2', '\xC2', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', '\xC2', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', '\xC4', '\xC6', '\a', '\x30', '\x2', '\x2', '\xC5', 
		'\xC7', '\t', '\x4', '\x2', '\x2', '\xC6', '\xC5', '\x3', '\x2', '\x2', 
		'\x2', '\xC7', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC6', '\x3', 
		'\x2', '\x2', '\x2', '\xC8', '\xC9', '\x3', '\x2', '\x2', '\x2', '\xC9', 
		':', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCE', '\a', '$', '\x2', '\x2', 
		'\xCB', '\xCD', '\v', '\x2', '\x2', '\x2', '\xCC', '\xCB', '\x3', '\x2', 
		'\x2', '\x2', '\xCD', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCF', 
		'\x3', '\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', '\x2', '\x2', '\x2', 
		'\xCF', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xCE', '\x3', '\x2', 
		'\x2', '\x2', '\xD1', '\xD2', '\a', '$', '\x2', '\x2', '\xD2', '<', '\x3', 
		'\x2', '\x2', '\x2', '\xD3', '\xD4', '\a', '\x31', '\x2', '\x2', '\xD4', 
		'\xD5', '\a', '\x31', '\x2', '\x2', '\xD5', '\xD9', '\x3', '\x2', '\x2', 
		'\x2', '\xD6', '\xD8', '\v', '\x2', '\x2', '\x2', '\xD7', '\xD6', '\x3', 
		'\x2', '\x2', '\x2', '\xD8', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xD9', 
		'\xDA', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xD7', '\x3', '\x2', '\x2', 
		'\x2', '\xDA', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xD9', '\x3', 
		'\x2', '\x2', '\x2', '\xDC', '\xDD', '\a', '\f', '\x2', '\x2', '\xDD', 
		'\xDE', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xDF', '\b', '\x1F', '\x2', 
		'\x2', '\xDF', '>', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE2', '\t', 
		'\x5', '\x2', '\x2', '\xE1', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xE2', 
		'\xE3', '\x3', '\x2', '\x2', '\x2', '\xE3', '\xE1', '\x3', '\x2', '\x2', 
		'\x2', '\xE3', '\xE4', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE5', '\x3', 
		'\x2', '\x2', '\x2', '\xE5', '\xE6', '\b', ' ', '\x2', '\x2', '\xE6', 
		'@', '\x3', '\x2', '\x2', '\x2', '\r', '\x2', 'J', '\x9F', '\xA4', '\xB7', 
		'\xBD', '\xC2', '\xC8', '\xCE', '\xD9', '\xE3', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
