//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BecasParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BecasParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IBecasParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.start_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart_rule([NotNull] BecasParser.Start_ruleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.start_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart_rule([NotNull] BecasParser.Start_ruleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstrucciones([NotNull] BecasParser.InstruccionesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.instrucciones"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstrucciones([NotNull] BecasParser.InstruccionesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruccion([NotNull] BecasParser.InstruccionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.instruccion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruccion([NotNull] BecasParser.InstruccionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_decl([NotNull] BecasParser.Var_declContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.var_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_decl([NotNull] BecasParser.Var_declContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.input_datos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput_datos([NotNull] BecasParser.Input_datosContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.input_datos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput_datos([NotNull] BecasParser.Input_datosContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.input_usuario"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInput_usuario([NotNull] BecasParser.Input_usuarioContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.input_usuario"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInput_usuario([NotNull] BecasParser.Input_usuarioContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.asignacion_suma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsignacion_suma([NotNull] BecasParser.Asignacion_sumaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.asignacion_suma"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsignacion_suma([NotNull] BecasParser.Asignacion_sumaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.ciclo_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCiclo_loop([NotNull] BecasParser.Ciclo_loopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.ciclo_loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCiclo_loop([NotNull] BecasParser.Ciclo_loopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.check_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCheck_block([NotNull] BecasParser.Check_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.check_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCheck_block([NotNull] BecasParser.Check_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.elseif_bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseif_bloque([NotNull] BecasParser.Elseif_bloqueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.elseif_bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseif_bloque([NotNull] BecasParser.Elseif_bloqueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.else_bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_bloque([NotNull] BecasParser.Else_bloqueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.else_bloque"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_bloque([NotNull] BecasParser.Else_bloqueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.condicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondicion([NotNull] BecasParser.CondicionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.condicion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondicion([NotNull] BecasParser.CondicionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.or_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr_cond([NotNull] BecasParser.Or_condContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.or_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr_cond([NotNull] BecasParser.Or_condContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.and_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_cond([NotNull] BecasParser.And_condContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.and_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_cond([NotNull] BecasParser.And_condContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.not_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNot_cond([NotNull] BecasParser.Not_condContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.not_cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNot_cond([NotNull] BecasParser.Not_condContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.comparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparacion([NotNull] BecasParser.ComparacionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.comparacion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparacion([NotNull] BecasParser.ComparacionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExp([NotNull] BecasParser.ExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExp([NotNull] BecasParser.ExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.numero"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumero([NotNull] BecasParser.NumeroContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.numero"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumero([NotNull] BecasParser.NumeroContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.valor_salida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValor_salida([NotNull] BecasParser.Valor_salidaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.valor_salida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValor_salida([NotNull] BecasParser.Valor_salidaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.salida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSalida([NotNull] BecasParser.SalidaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.salida"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSalida([NotNull] BecasParser.SalidaContext context);
}
