//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from BecasParser.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBecasParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class BecasParserBaseListener : IBecasParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.start_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart_rule([NotNull] BecasParser.Start_ruleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.start_rule"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart_rule([NotNull] BecasParser.Start_ruleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstrucciones([NotNull] BecasParser.InstruccionesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.instrucciones"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstrucciones([NotNull] BecasParser.InstruccionesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruccion([NotNull] BecasParser.InstruccionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.instruccion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruccion([NotNull] BecasParser.InstruccionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.var_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_decl([NotNull] BecasParser.Var_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.var_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_decl([NotNull] BecasParser.Var_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.input_datos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_datos([NotNull] BecasParser.Input_datosContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.input_datos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_datos([NotNull] BecasParser.Input_datosContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.input_usuario"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_usuario([NotNull] BecasParser.Input_usuarioContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.input_usuario"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_usuario([NotNull] BecasParser.Input_usuarioContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.asignacion_suma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsignacion_suma([NotNull] BecasParser.Asignacion_sumaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.asignacion_suma"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsignacion_suma([NotNull] BecasParser.Asignacion_sumaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.ciclo_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCiclo_loop([NotNull] BecasParser.Ciclo_loopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.ciclo_loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCiclo_loop([NotNull] BecasParser.Ciclo_loopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.check_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCheck_block([NotNull] BecasParser.Check_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.check_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCheck_block([NotNull] BecasParser.Check_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.elseif_bloque"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseif_bloque([NotNull] BecasParser.Elseif_bloqueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.elseif_bloque"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseif_bloque([NotNull] BecasParser.Elseif_bloqueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.else_bloque"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_bloque([NotNull] BecasParser.Else_bloqueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.else_bloque"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_bloque([NotNull] BecasParser.Else_bloqueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.condicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondicion([NotNull] BecasParser.CondicionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.condicion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondicion([NotNull] BecasParser.CondicionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.or_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_cond([NotNull] BecasParser.Or_condContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.or_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_cond([NotNull] BecasParser.Or_condContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.and_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_cond([NotNull] BecasParser.And_condContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.and_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_cond([NotNull] BecasParser.And_condContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.not_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot_cond([NotNull] BecasParser.Not_condContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.not_cond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot_cond([NotNull] BecasParser.Not_condContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.comparacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparacion([NotNull] BecasParser.ComparacionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.comparacion"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparacion([NotNull] BecasParser.ComparacionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] BecasParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] BecasParser.ExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.numero"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumero([NotNull] BecasParser.NumeroContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.numero"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumero([NotNull] BecasParser.NumeroContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.valor_salida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValor_salida([NotNull] BecasParser.Valor_salidaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.valor_salida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValor_salida([NotNull] BecasParser.Valor_salidaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BecasParser.salida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSalida([NotNull] BecasParser.SalidaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BecasParser.salida"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSalida([NotNull] BecasParser.SalidaContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
